# Generated by Django 3.2.1 on 2021-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('designation', models.TextField(max_length=100)),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
